import type { Database } from "bun:sqlite";

export type DbObjectType = "table" | "index" | "view";

export interface SchemaColumn {
  name: string;
  type: string;
  notNull: boolean;
  defaultValue: string | null;
  isPrimaryKey: boolean;
}

export interface SchemaObject {
  type: DbObjectType;
  name: string;
  sql: string;
  normalizedSql: string;
}

export interface SchemaSnapshot {
  tables: Map<string, SchemaObject>;
  indexes: Map<string, SchemaObject>;
  views: Map<string, SchemaObject>;
  columnsByTable: Map<string, Map<string, SchemaColumn>>;
  virtualTables: Set<string>;
}

interface SqliteMasterRow {
  type: DbObjectType;
  name: string;
  sql: string;
}

interface TableInfoRow {
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
}

function normalizeSql(sql: string): string {
  return sql
    .replace(/\s+/g, " ")
    .replace(/\s*\(\s*/g, "(")
    .replace(/\s*\)\s*/g, ")")
    .replace(/\s*,\s*/g, ",")
    .trim()
    .replace(/;$/, "")
    .toLowerCase();
}

function isVirtualTableSql(sql: string): boolean {
  return sql.trim().toUpperCase().startsWith("CREATE VIRTUAL TABLE");
}

function quoteSqliteIdentifier(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

export function inspectSchema(db: Database): SchemaSnapshot {
  const rows = db
    .query<SqliteMasterRow, []>(
      `SELECT type, name, sql
       FROM sqlite_master
       WHERE type IN ('table', 'index', 'view')
         AND name NOT LIKE 'sqlite_%'
         AND sql IS NOT NULL`,
    )
    .all();

  const virtualTables = new Set<string>();
  for (const row of rows) {
    if (row.type === "table" && isVirtualTableSql(row.sql)) {
      virtualTables.add(row.name);
    }
  }

  const tables = new Map<string, SchemaObject>();
  const indexes = new Map<string, SchemaObject>();
  const views = new Map<string, SchemaObject>();

  for (const row of rows) {
    if (row.type === "table") {
      // Skip internal backing tables generated by virtual tables (fts5, etc.).
      if ([...virtualTables].some((vt) => row.name.startsWith(`${vt}_`) && row.name !== vt)) {
        continue;
      }
    }

    const object: SchemaObject = {
      type: row.type,
      name: row.name,
      sql: row.sql,
      normalizedSql: normalizeSql(row.sql),
    };

    if (row.type === "table") tables.set(row.name, object);
    else if (row.type === "index") indexes.set(row.name, object);
    else views.set(row.name, object);
  }

  const columnsByTable = new Map<string, Map<string, SchemaColumn>>();
  for (const tableName of tables.keys()) {
    const pragmaRows = db
      .query<TableInfoRow, []>(`PRAGMA table_info(${quoteSqliteIdentifier(tableName)})`)
      .all();
    const columns = new Map<string, SchemaColumn>();
    for (const row of pragmaRows) {
      columns.set(row.name, {
        name: row.name,
        type: row.type,
        notNull: row.notnull === 1,
        defaultValue: row.dflt_value,
        isPrimaryKey: row.pk > 0,
      });
    }
    columnsByTable.set(tableName, columns);
  }

  return {
    tables,
    indexes,
    views,
    columnsByTable,
    virtualTables,
  };
}
